displayName=Hitsplat Styles
author=Mark7625
support=https://github.com/Mark7625/runelite-external-plugins/tree/hitsplat-styles
description=Replaces hitsplats with art from an earlier era - 2002, 2010 or 2011
tags=hitsplat,hitsplats,damage,combat,retro,fade,style,styles,2002,2010,2011
plugins=io.mark.hitsplats.HitsplatStylesPlugin
build=standard
version=1.0