displayName=RuneCast OBS
author=Mark7625
support=https://github.com/Mark7625/runelite-external-plugins
description=Provides HP information for OBS browser sources
tags=obs,streaming,hp,health
plugins=io.mark.runecast.RuneCastPlugin