displayName=HQ Item Icons
author=Mark7625
support=https://github.com/Mark7625/runelite-external-plugins/tree/hd-item-icons
description=Sharper, high quality item icons
tags=hq,hd,item,icons,inventory,bank,antialiasing
plugins=io.mark.hditemicons.HdItemIconsPlugin
build=standard
version=1.1